OBJS = ../build/lista_encadeada.o ../build/matrizes.o ../build/grafos.o ../build/dfs.o ../build/bfs.o ../build/fechotransitivo.o ../build/kosaraju.o ../build/coloracao.o

%:%.c
	gcc -g -I../include $(OBJS) $^ -o $@
